### PR TITLE
Logger for XPRA reports & change of application log sub-object to customer name space

### PR DESCRIPTION
**Pull request by kjetil-kilhavn**
I have implemented a compatible logger for XPRA report execution which will add messages to the transport log instead of creating an application log in client zero.

As I am still rather new to git I have probably made a few mistakes, and there's a little more included here than what was strictly needed. For instance, I should probably not have staged the package - I see the application component has been committed as a change. Sorry about that. 
One thing that should be included, but should probably have been in a separate pull request is the change from 'LOGGER' to 'ZCL_LOGGER' as application log sub-object for unit tests to avoid problems with name space.

I don't know why the zcl_logger.clas.xml is updated with removal of the class documentation. I have even tried changing the documentation and activating it, but it just won't come back. 

Unit tests.... yes, I should get started on that topic.

If there's too many beginner mistakes to fix, please reject the pull request. In a while I should be able to create one (or several) that can be accepted more smoothly.

### CODE REVIEW

**Comment by andkopp** [comment]
Thank you for your pull request. I am always happy with every contribution. I need time to dig into it (I don't know XPRA). And I'd like to do a pull request with the refactoring I have done first so maybe you will have to adapt some of the code then.

**Comment by kjetil-kilhavn** [comment]
XPRA is simply a mechanism to execute a report as part of a transport import, so it's main use (AFAIK) is to initialize values for existing records in tables, e.g. if you add a field to a table and the existing records all should have the same value or can get their value calculated. This is particularly important when there are other changes in the code in the same transport, and these depend on the value in the new field. By using an XPRA you ensure that the new code works as intended immediately and there is no need to execute an initialization report manually.
XPRAs can of course be used for anything, they are just reports executed without taking a variant into consideration (uses the default values for all parameters and select-options) and executed in client zero. Client zero is the main reason output should be added to the transport log. That's what the new class does. I guess an option could be added to optionally also save the messages in an application log, although I have never seen a need for that.
No problem with waiting, I discovered your refactoring initiative after submitting my pull request. I can adjust the code and create a new pull request later.

**Comment by andkopp** [comment]
I just merged all the refactoring into the master branch. Could you adopt your coding?

**Comment by kjetil-kilhavn** [comment]
I will. I am working Monday and Tuesday before taking some days off, so I am not sure if I can find the time this coming week, but will do it as soon as I find time.
However, I am not very git or github experienced, so how should we handle this? Will you cancel this pull request, and I create a new one after updating the code?

**Pull request closed without merging**
